This might fix the problem on cdash with oracle.mdmt and precise.mdmt
libdl is missing

-- Building CGNS & adfviewer...
CMake Error at cmake_modules/CFS_macros.cmake:29 (MESSAGE):
  Build of CGNS & adfviewer failed!

  Here are the last 12 lines of the build logfile
  '/home/oracle/Documents/dev/CFS_BUILD_NIGHTLY/tmp/build_cgns.log':

  

  H5PL.c:(.text+0xb7f): undefined reference to `dlerror'

  H5PL.c:(.text+0xb9f): undefined reference to `dlsym'

  
  /home/oracle/Documents/dev/CFS_BUILD_NIGHTLY/lib64/RHEL_6_X86_64/libhdf5.a(H5PL.c.o):
  In function `H5PL__search_table':

  H5PL.c:(.text+0xf61): undefined reference to `dlsym'